@startuml
:Agente: --> (Enviar Solicitud credito)
(Enviar Solicitud de crédito personal) --|> (Enviar Solicitud credito)
(Enviar Solicitud de crédito empresarial) --|> (Enviar Solicitud credito)
@enduml