@startuml
:Cliente Bancario:
:Cliente Corporativo: --|> :Cliente Bancario:
:Cliente Normal: --|> :Cliente Bancario:
note "Actor Antecesor" as n1
note "Actor Descendente" as n2
n1 --> :Cliente Bancario:
n2 --> :Cliente Normal:
n2 --> :Cliente Corporativo:
@enduml